name: NPM install
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: |
          mkdir my-app
          cd my-app
          npm init -y
          npm install @unomed/react-native-matrix-sdk
